apiVersion: apps/v1
kind: Deployment
metadata:
  name: deeproot-ai
  labels:
    app: deeproot-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deeproot-ai
  template:
    metadata:
      labels:
        app: deeproot-ai
    spec:
      containers:
      - name: deeproot-ai
        image: asia-south1-docker.pkg.dev/hbl-uat-delta-prj-spk-4d/isaac/deeprootai-v2:testing-3
        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 8000

        env:
        - name: ES_HOST
          value: "http://smartwealth-elasticsearch-es-http.services-uat-new.svc.cluster.local:9200"
        
        - name: ES_LOG_INDEX
          value: "otel-logs"

        - name: ES_TRACE_INDEX
          value: "otel-traces"
        
        - name: ES_USER
          value: "wealth_es_admin"

        - name: ES_PASS
          value: "Wealthadmin@123"

        - name: OLLAMA_URL
          value: "http://ollama:11434"

        - name: OLLAMA_MODEL
          value: "mistral"

        - name: LOG_LEVEL
          value: "INFO"

        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "5"
            memory: "10Gi"

---
apiVersion: v1
kind: Service
metadata:
  name: deeproot-api
spec:
  selector:
    app: deeproot-ai
  ports:
    - name: http
      port: 8080
      targetPort: 8000
